import { copyFile, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { buildLock, serializeLock, validateLock } from '../src/lock.js'
import { createFixture, importedAsset, validManifest } from './fixtures.js'

const cleanups: Array<() => Promise<void>> = []

afterEach(async () => {
  await Promise.all(cleanups.splice(0).map((cleanup) => cleanup()))
})

describe('media lock', () => {
  it('creates a hash-addressed lock entry from a real WebP', async () => {
    const fixture = await createFixture()
    cleanups.push(fixture.cleanup)

    const lock = await buildLock(fixture.manifestPath)

    expect(lock).toMatchObject({
      version: 1,
      publisherVersion: '0.1.0',
      namespace: 'blog',
      cdnBaseUrl: 'https://pic.minyako.top',
    })
    expect(lock.assets).toHaveLength(1)
    expect(lock.assets[0]).toMatchObject({
      id: 'home-hero-01',
      file: 'assets/home/hero-01.webp',
      contentType: 'image/webp',
      cacheControl: 'public, max-age=31536000, immutable',
      width: 64,
      height: 32,
    })
    expect(lock.assets[0]?.sha256).toMatch(/^[a-f0-9]{64}$/)
    expect(lock.assets[0]?.objectKey).toMatch(
      /^blog\/site\/home\/hero-01-[a-f0-9]{64}\.webp$/,
    )
    expect(lock.assets[0]?.url).toBe(
      `https://pic.minyako.top/${lock.assets[0]?.objectKey}`,
    )
  })

  it('sorts lock entries by stable id and emits deterministic JSON', async () => {
    const fixture = await createFixture()
    cleanups.push(fixture.cleanup)
    await copyFile(fixture.webpPath, join(fixture.media, 'assets', 'home', 'hero-02.webp'))
    await fixture.writeManifest(validManifest([
      importedAsset({
        id: 'z-cover',
        file: 'assets/home/hero-02.webp',
        objectBase: 'posts/z/cover',
      }),
      importedAsset({ id: 'a-cover', objectBase: 'posts/a/cover' }),
    ]))

    const lock = await buildLock(fixture.manifestPath)
    const first = serializeLock(lock)
    const second = serializeLock(await buildLock(fixture.manifestPath))

    expect(lock.assets.map((asset) => asset.id)).toEqual(['a-cover', 'z-cover'])
    expect(first).toBe(second)
    expect(first.endsWith('\n')).toBe(true)
  })

  it('rejects a derivative whose bytes are PNG despite a WebP name', async () => {
    const fixture = await createFixture()
    cleanups.push(fixture.cleanup)
    const png = await import('sharp').then(({ default: sharp }) =>
      sharp({
        create: {
          width: 16,
          height: 16,
          channels: 3,
          background: { r: 1, g: 2, b: 3 },
        },
      }).png().toBuffer(),
    )
    await writeFile(fixture.webpPath, png)

    await expect(buildLock(fixture.manifestPath)).rejects.toThrow('Expected WebP')
  })

  it('fails when the committed lock differs from regenerated bytes', async () => {
    const fixture = await createFixture()
    cleanups.push(fixture.cleanup)
    const lock = await buildLock(fixture.manifestPath)
    await writeFile(fixture.lockPath, serializeLock({ ...lock, publisherVersion: 'stale' }), 'utf8')

    await expect(validateLock(fixture.manifestPath, fixture.lockPath))
      .rejects.toThrow('media lock is stale')

    expect(await readFile(fixture.lockPath, 'utf8')).toContain('stale')
  })
})
